import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'
import Header from '../components/Header'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
    <Header/>
      {/* <div
      style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white', zIndex: -1,
        backgroundImage:`url(/images/b5.svg)`,
        backgroundSize:"cover",
        width:"100vw",
        height:"100vh"

      }}
      ></div> */}
      <Head>
        <title>Jibby: Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="http://fonts.cdnfonts.com/css/somatic" rel="stylesheet"/>
      </Head>

      <Parallax pages={2} style={{ top: '0', left: '0' }}>

        <ParallaxLayer offset={0} speed={0.5} style={{ backgroundColor: "#20253A" }} />
        <ParallaxLayer offset={0} speed={3} style={{  width: "100vw", height: "100vh" }}>
          <div style={{ backgroundImage: `url(/images/b4.svg)`, backgroundSize: "cover", overflow: "hidden", width: "100vw", height: "100vh", }}></div>
          <div style={{ backgroundColor: `#1E2236`, backgroundSize: "cover", width: "100vw", height: "100vh", }}></div>
        </ParallaxLayer>

        <ParallaxLayer offset={0} speed={2} style={{  width: "100vw", height: "100vh" }}>
          <div style={{ backgroundImage: `url(/images/b3.svg)`, backgroundSize: "cover", overflow: "hidden", width: "100vw", height: "100vh", }}></div>
          <div style={{ backgroundColor: `#1C2033`, backgroundSize: "cover", width: "100vw", height: "100vh", }}></div>
        </ParallaxLayer>
        <ParallaxLayer offset={0} speed={1} style={{  width: "100vw", height: "100vh", }}>
         
          <div style={{ backgroundImage: `url(/images/b2.svg)`, backgroundSize: "cover", overflow: "hidden", width: "100vw", height: "100vh", }}></div>
          <div style={{ backgroundColor: `#1A1E2F`, backgroundSize: "cover", width: "100vw", height: "100vh", }}></div>
         
        </ParallaxLayer>
        <ParallaxLayer offset={0} speed={0.2} style={{  width: "100vw", height: "100vh", }}>
          <div style={{ backgroundImage: `url(/images/b1.svg)`, backgroundSize: "cover", overflow: "hidden", width: "100vw", height: "100vh", }}></div>
          <div style={{ backgroundColor: `#181C2C`, backgroundSize: "cover", width: "100vw", height: "100vh", }}></div>

        </ParallaxLayer>
        <ParallaxLayer offset={1} speed={1} style={{   backgroundColor:"#181C2C" }}/>
        <ParallaxLayer offset={0} speed={1}>
          <Image src="/images/motto.svg" width={200} height={200} alt=""></Image>
        </ParallaxLayer>


        {/* <ParallaxLayer offset={1} speed={2} style={{   backgroundColor:"#181C2C" }}/>
        <ParallaxLayer offset={0} speed={1.5}  style={{ backgroundColor:"#1A1E2F" }}/>
        <ParallaxLayer offset={0} speed={1}   style={{   backgroundColor:"#1C2033" }}/>
        <ParallaxLayer offset={0} speed={0.5}    style={{  backgroundColor:"#1E2236" }}/>
        <ParallaxLayer offset={0} speed={0.5}   style={{  backgroundColor:"#20253A" }}/> */}





        {/* <ParallaxLayer offset={0} style={{ backgroundImage:`url(/images/b1.svg)`, backgroundSize:"cover", overflow:"hidden", width:"100vw", height:"100vh"  }} /> */}
        {/* <ParallaxLayer
          offset={0}
          sticky={{ start: 0, end: 1 }}
          style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: -1 }}>
          <h1>Hello</h1>
        </ParallaxLayer>



        <ParallaxLayer
          offset={1}
          sticky={{ start: 1, end: 2 }}
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            color: 'white', zIndex: -1,
            backgroundColor:"red",
            backgroundImage:`url(${b5})`,
            backgroundSize:"cover"

          }}>
          <h1>Nice To meet you!</h1>
        </ParallaxLayer> */}


      </Parallax>
    </div>
  )
}

export default Home
